// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bellon.API.Liquidacion.DataBase.Models;

[Table("Clasificaciones", Schema = "ConsumoInterno")]
public partial class Clasificaciones
{
    [Key]
    public int id_clasificacion { get; set; }

    [Required]
    [StringLength(100)]
    public string id_grupo_cont_producto_general { get; set; }

    [Required]
    [StringLength(50)]
    public string codigo_clasificacion { get; set; }

    [Required]
    public string descripcion { get; set; }

    public bool estado { get; set; }
}