// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bellon.API.Liquidacion.DataBase.Models;

[Table("EstadosSolicitudes", Schema = "ConsumoInterno")]
public partial class EstadosSolicitudes
{
    [Key]
    public int id_estado_solicitud { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string descripcion { get; set; }

    public bool estado { get; set; }

    [InverseProperty("id_estado_solicitudNavigation")]
    public virtual ICollection<CabeceraSolicitudes> CabeceraSolicitudes { get; set; } = new List<CabeceraSolicitudes>();
}