// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bellon.API.Liquidacion.DataBase.Models;

[Table("LineasSolicitudes", Schema = "ConsumoInterno")]
public partial class LineasSolicitudes
{
    [Key]
    public int id_linea_solicitud { get; set; }

    public int cabecera_solicitud_id { get; set; }

    [Required]
    [StringLength(20)]
    public Guid id_producto { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string descripcion { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal precio_unitario { get; set; }

    public int cantidad { get; set; }

    [StringLength(20)]
    public Guid id_unidad_medida { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string codigo_unidad_medida { get; set; }
    
    public Guid? almacen_id { get; set; }

    public string? almacen_codigo { get; set; }

    [Unicode(false)]
    public string nota { get; set; }

    [ForeignKey("cabecera_solicitud_id")]
    [InverseProperty("LineasSolicitudes")]
    public virtual CabeceraSolicitudes cabecera_solicitud { get; set; }
}