// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bellon.API.Liquidacion.DataBase.Models;


[Table("NoSeries", Schema = "ConsumoInterno")]
[Index("codigo", Name = "FP_NoSeries_UQ_Codigo", IsUnique = true)]
public partial class NoSeries2
{
    [Key]
    public int id_no_serie { get; set; }

    [Required]
    [StringLength(10)]
    public string codigo { get; set; }

    [Required]
    [StringLength(50)]
    public string descripcion { get; set; }

    [Required]
    [StringLength(20)]
    public string secuencia_inicial { get; set; }

    [Required]
    [StringLength(20)]
    public string ultima_secuencia_utilizada { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fecha_ultima_secuencia_utilizada { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fecha_creado { get; set; }

    [Required]
    [StringLength(100)]
    public string creado_por { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha_modificado { get; set; }

    [StringLength(100)]
    public string modificado_por { get; set; }
}