// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bellon.API.Liquidacion.DataBase.Models;

[Table("Posiciones", Schema = "ConsumoInterno")]
public partial class Posiciones
{
    [Key]
    public int posicion_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string descripcion { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal limite_maximo_permitido { get; set; }

    [InverseProperty("posicion")]
    public virtual ICollection<Usuarios> Usuarios { get; set; } = new List<Usuarios>();
}