// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bellon.API.Liquidacion.DataBase.Models;

[Table("Agentes", Schema = "Liquidacion")]
public partial class Agentes
{
    [Key]
    public int id_agente { get; set; }

    [StringLength(100)]
    public string nombre { get; set; } = null!;

    [StringLength(3)]
    public string tipo { get; set; } = null!;

    public bool estado { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fecha_creado { get; set; }

    [StringLength(100)]
    public string creado_por { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime? fecha_modificado { get; set; }

    [StringLength(100)]
    public string? modificado_por { get; set; }

    [InverseProperty("agente")]
    public virtual ICollection<CabeceraLiquidaciones> CabeceraLiquidaciones { get; set; } = new List<CabeceraLiquidaciones>();

    [InverseProperty("agente")]
    public virtual ICollection<CabeceraLlegadas> CabeceraLlegadas { get; set; } = new List<CabeceraLlegadas>();

    [InverseProperty("agente")]
    public virtual ICollection<HistCabeceraLiquidaciones> HistCabeceraLiquidaciones { get; set; } = new List<HistCabeceraLiquidaciones>();

    [InverseProperty("agente")]
    public virtual ICollection<HistCabeceraLlegadas> HistCabeceraLlegadas { get; set; } = new List<HistCabeceraLlegadas>();
}