// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bellon.API.Liquidacion.DataBase.Models;

[Table("CabeceraLlegadas", Schema = "Liquidacion")]
public partial class CabeceraLlegadas
{
    [Key]
    public int id_cabecera_llegada { get; set; }

    public int no_serie_id { get; set; }

    [StringLength(20)]
    public string no_documento { get; set; } = null!;

    public DateOnly fecha_documento { get; set; }

    public DateOnly fecha_registro { get; set; }

    [StringLength(100)]
    public string id_documento_origen { get; set; } = null!;

    [StringLength(20)]
    public string no_documento_origen { get; set; } = null!;

    [StringLength(20)]
    public string no_documento_previo { get; set; } = null!;

    [StringLength(20)]
    public string id_proveedor { get; set; } = null!;

    [StringLength(100)]
    public string no_proveedor { get; set; } = null!;

    [StringLength(100)]
    public string nombre_proveedor { get; set; } = null!;

    [StringLength(30)]
    public string no_factura_proveedor { get; set; } = null!;

    [StringLength(30)]
    public string no_almacen_us { get; set; } = null!;

    [StringLength(30)]
    public string transportista { get; set; } = null!;

    [Column(TypeName = "decimal(38, 20)")]
    public decimal cantidad_pieza { get; set; }

    [StringLength(100)]
    public string id_peso { get; set; } = null!;

    [StringLength(10)]
    public string codigo_peso { get; set; } = null!;

    [Column(TypeName = "decimal(38, 20)")]
    public decimal cantidad_peso { get; set; }

    [StringLength(100)]
    public string id_volumen { get; set; } = null!;

    [StringLength(10)]
    public string codigo_volumen { get; set; } = null!;

    [Column(TypeName = "decimal(38, 20)")]
    public decimal? cantidad_volumen { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal? total { get; set; }

    public int agente_id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fecha_creado { get; set; }

    [StringLength(100)]
    public string creado_por { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime? fecha_modificado { get; set; }

    [StringLength(100)]
    public string? modificado_por { get; set; }

    [InverseProperty("cabecera_llegada")]
    public virtual ICollection<LineaLlegadas> LineaLlegadas { get; set; } = new List<LineaLlegadas>();

    [ForeignKey("agente_id")]
    [InverseProperty("CabeceraLlegadas")]
    public virtual Agentes agente { get; set; } = null!;

    [ForeignKey("no_serie_id")]
    [InverseProperty("CabeceraLlegadas")]
    public virtual NoSeries no_serie { get; set; } = null!;
}