// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bellon.API.Liquidacion.DataBase.Models;

[Table("CabeceraTransito", Schema = "Liquidacion")]
public partial class CabeceraTransito
{
    [Key]
    public int id_cabecera_transito { get; set; }

    public int no_serie_id { get; set; }

    [StringLength(20)]
    public string no_documento { get; set; } = null!;

    public DateOnly fecha_documento { get; set; }

    public DateOnly fecha_registro { get; set; }

    [StringLength(50)]
    public string nombre_proveedor { get; set; } = null!;

    [StringLength(50)]
    public string naviera { get; set; } = null!;

    [StringLength(50)]
    public string no_conocimiento_embarque { get; set; } = null!;

    [StringLength(50)]
    public string no_sello { get; set; } = null!;

    [StringLength(50)]
    public string no_buque { get; set; } = null!;

    public int tipo_contenedor_id { get; set; }

    [StringLength(30)]
    public string no_contenedor { get; set; } = null!;

    public DateOnly fecha_embarque { get; set; }

    [StringLength(30)]
    public string puerto_embarque { get; set; } = null!;

    public DateOnly fecha_desembarque { get; set; }

    [StringLength(30)]
    public string puerto_desembarque { get; set; } = null!;

    [StringLength(100)]
    public string almacen_id { get; set; } = null!;

    [StringLength(20)]
    public string almacen_codigo { get; set; } = null!;

    public DateOnly fecha_estimada { get; set; }

    [StringLength(100)]
    public string detalle_mercancia { get; set; } = null!;

    [Column(TypeName = "decimal(38, 20)")]
    public decimal total { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fecha_creado { get; set; }

    [StringLength(100)]
    public string creado_por { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime? fecha_modificado { get; set; }

    [StringLength(100)]
    public string? modificado_por { get; set; }

    [InverseProperty("cabecera_transito")]
    public virtual ICollection<LineaTransitos> LineaTransitos { get; set; } = new List<LineaTransitos>();

    [ForeignKey("no_serie_id")]
    [InverseProperty("CabeceraTransito")]
    public virtual NoSeries no_serie { get; set; } = null!;

    [ForeignKey("tipo_contenedor_id")]
    [InverseProperty("CabeceraTransito")]
    public virtual TipoContenedores tipo_contenedor { get; set; } = null!;
}