// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bellon.API.Liquidacion.DataBase.Models;

[Table("CargosAdicionales", Schema = "Liquidacion")]
public partial class CargosAdicionales
{
    [Key]
    public int id_cargo_adicional { get; set; }

    public int cabecera_liquidacion_id { get; set; }

    [StringLength(100)]
    public string id_cargo_producto { get; set; } = null!;

    [StringLength(20)]
    public string no_cargo_producto { get; set; } = null!;

    [StringLength(100)]
    public string descripcion_cargo_producto { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime fecha_documento { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal monto_documento { get; set; }

    [StringLength(100)]
    public string observacion { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime fecha_creado { get; set; }

    [StringLength(100)]
    public string creado_por { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime? fecha_modificado { get; set; }

    [StringLength(100)]
    public string? modificado_por { get; set; }

    [ForeignKey("cabecera_liquidacion_id")]
    [InverseProperty("CargosAdicionales")]
    public virtual CabeceraLiquidaciones cabecera_liquidacion { get; set; } = null!;
}