// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bellon.API.Liquidacion.DataBase.Models;

[Table("CargosFacturaLiquidacion", Schema = "Liquidacion")]
public partial class CargosFacturaLiquidacion
{
    [Key]
    public int id_cargo_factura_liquidacion { get; set; }

    public int cabecera_liquidacion_id { get; set; }

    [StringLength(20)]
    public string no_documento_liquidacion { get; set; } = null!;

    [StringLength(100)]
    public string id_factura { get; set; } = null!;

    [StringLength(20)]
    public string no_factura { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime fecha { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal importe { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal importe_sin_iva { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fecha_creado { get; set; }

    [StringLength(100)]
    public string creado_por { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime? fecha_modificado { get; set; }

    [StringLength(100)]
    public string? modificado_por { get; set; }

    [StringLength(20)]
    public string no_cargo_producto;

    [StringLength(100)]
    public string? referencia_cargo_producto;

    [StringLength(100)]
    public string no_proveedor;

    [StringLength(100)]
    public string nombre_proveedor;
}