// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bellon.API.Liquidacion.DataBase.Models;

[Table("CodigoArancelarios", Schema = "Liquidacion")]
public partial class CodigoArancelarios
{
    [Key]
    public int id_codigo_arancelario { get; set; }

    [StringLength(100)]
    public string id_cod_arancelario { get; set; } = null!;

    [StringLength(20)]
    public string no_cod_arancelario { get; set; } = null!;

    [StringLength(100)]
    public string descripcion_cod_arancelario { get; set; } = null!;

    [StringLength(100)]
    public string id_pais { get; set; } = null!;

    [StringLength(10)]
    public string codigo_pais { get; set; } = null!;

    [Column(TypeName = "decimal(38, 20)")]
    public decimal porciento_selectivo { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal porciento_gravamen { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fecha_creado { get; set; }

    [StringLength(100)]
    public string creado_por { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime? fecha_modificado { get; set; }

    [StringLength(100)]
    public string? modificado_por { get; set; }

    [InverseProperty("codigo_arancelario")]
    public virtual ICollection<HistLineaLiquidaciones> HistLineaLiquidaciones { get; set; } = new List<HistLineaLiquidaciones>();

    [InverseProperty("codigo_arancelario")]
    public virtual ICollection<LineaLiquidaciones> LineaLiquidaciones { get; set; } = new List<LineaLiquidaciones>();
}