// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bellon.API.Liquidacion.DataBase.Models;

[Table("HistLineaLiquidaciones", Schema = "Liquidacion")]
public partial class HistLineaLiquidaciones
{
    [Key]
    public int id_hist_linea_liquidacion { get; set; }

    public int hist_cabecera_liquidacion_id { get; set; }

    public int hist_cabecera_transito_id { get; set; }

    [StringLength(100)]
    public string id_producto { get; set; } = null!;

    [StringLength(20)]
    public string no_producto { get; set; } = null!;

    [StringLength(50)]
    public string descripcion_producto { get; set; } = null!;

    [StringLength(50)]
    public string referencia_producto { get; set; } = null!;

    public int codigo_arancelario_id { get; set; }

    [StringLength(20)]
    public string codigo_pais_origen { get; set; } = null!;

    [StringLength(100)]
    public string id_unidad_medida { get; set; } = null!;

    [StringLength(10)]
    public string codigo_unidad_medida { get; set; } = null!;

    [Column(TypeName = "decimal(38, 20)")]
    public decimal cantidad { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal fob_aduana_us { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal total_cif { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal total_gravamen { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal total_selectivo { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal tasa_itbis { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal total_itbis { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal total_general { get; set; }

    [StringLength(100)]
    public string almacen_id { get; set; } = null!;

    [StringLength(20)]
    public string almacen_codigo { get; set; } = null!;

    [Column(TypeName = "decimal(38, 20)")]
    public decimal costo_producto_rd { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal costo_producto_us { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal tasa_liquidacion { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal ultimo_costo_producto_rd { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal importe_us { get; set; }

    [StringLength(100)]
    public string id_pais_origen { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime fecha_creado { get; set; }

    [StringLength(100)]
    public string creado_por { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime? fecha_modificado { get; set; }

    [StringLength(100)]
    public string? modificado_por { get; set; }

    [ForeignKey("codigo_arancelario_id")]
    [InverseProperty("HistLineaLiquidaciones")]
    public virtual CodigoArancelarios codigo_arancelario { get; set; } = null!;

    [ForeignKey("hist_cabecera_liquidacion_id")]
    [InverseProperty("HistLineaLiquidaciones")]
    public virtual HistCabeceraLiquidaciones hist_cabecera_liquidacion { get; set; } = null!;

    [ForeignKey("hist_cabecera_transito_id")]
    [InverseProperty("HistLineaLiquidaciones")]
    public virtual HistCabeceraTransitos hist_cabecera_transito { get; set; } = null!;
}