// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bellon.API.Liquidacion.DataBase.Models;

[Table("HistLineaLlegadas", Schema = "Liquidacion")]
public partial class HistLineaLlegadas
{
    [Key]
    public int id_hist_linea_llegada { get; set; }

    public int hist_cabecera_llegada_id { get; set; }

    [StringLength(100)]
    public string id_producto { get; set; } = null!;

    [StringLength(20)]
    public string no_producto { get; set; } = null!;

    [StringLength(50)]
    public string descripcion_producto { get; set; } = null!;

    [StringLength(50)]
    public string referencia_producto { get; set; } = null!;

    [StringLength(100)]
    public string id_unidad_medida { get; set; } = null!;

    [StringLength(10)]
    public string codigo_unidad_medida { get; set; } = null!;

    [StringLength(100)]
    public string id_pais { get; set; } = null!;

    [StringLength(20)]
    public string codigo_pais_origen { get; set; } = null!;

    [Column(TypeName = "decimal(38, 20)")]
    public decimal cantidad_origen { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal cantidad { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal precio_unitario { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal costo_unitario { get; set; }

    [Column(TypeName = "decimal(38, 20)")]
    public decimal costo_unitario_directo { get; set; }

    [StringLength(100)]
    public string almacen_id { get; set; } = null!;

    [StringLength(20)]
    public string almacen_codigo { get; set; } = null!;

    [Column(TypeName = "decimal(38, 20)")]
    public decimal total { get; set; }

    [StringLength(100)]
    public string id_cod_arancelario { get; set; } = null!;

    [StringLength(20)]
    public string no_cod_arancelario { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime fecha_creado { get; set; }

    [StringLength(100)]
    public string creado_por { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime? fecha_modificado { get; set; }

    [StringLength(100)]
    public string? modificado_por { get; set; }

    [ForeignKey("hist_cabecera_llegada_id")]
    [InverseProperty("HistLineaLlegadas")]
    public virtual HistCabeceraLlegadas hist_cabecera_llegada { get; set; } = null!;
}