// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bellon.API.Liquidacion.DataBase.Models;

[Table("Notas", Schema = "Liquidacion")]

public partial class Notas
{
    [Key]
    public int id_nota { get; set; }

    public int id_documento { get; set; }

    [StringLength(3)]
    public string tipo_documento { get; set; }

    [StringLength(20)]
    public string no_documento { get; set; }

    [StringLength(100)]
    public string? usuario_destino { get; set; }

    [StringLength(150)]
    public string descripcion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fecha_creado { get; set; }

    [StringLength(100)]
    public string creado_por { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha_modificado { get; set; }

    [StringLength(100)]
    public string? modificado_por { get; set; }

}