// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bellon.API.Liquidacion.DataBase.Models;

[Table("OrdenesTransferencia", Schema = "Liquidacion")]
public partial class OrdenesTransferencia
{
    [Key]
    [StringLength(100)]
    public string id_orden_transferencia { get; set; }

    [StringLength(20)]
    public string no_orden_transferencia { get; set; }

    public int hist_cabecera_transito_id { get; set; }

    public int hist_cabecera_liquidacion_id { get; set; }

    [StringLength(100)]
    public string id_orden_envio { get; set; } = null!;

    [StringLength(20)]
    public string no_orden_envio { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime fecha_creado { get; set; }

    [StringLength(100)]
    public string creado_por { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime? fecha_modificado { get; set; }

    [StringLength(100)]
    public string? modificado_por { get; set; }

    
    [ForeignKey("hist_cabecera_transito_id")]
    [InverseProperty("OrdenesTransferencia")]
    public virtual HistCabeceraTransitos hist_cabecera_transito { get; set; } = null!;
}