// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bellon.API.Liquidacion.DataBase.Models;

[Table("vRecepcionMercancia", Schema = "Liquidacion")]
public partial class RecepcionMercancia
{
    public string documento_recepcion_mercancia { get; set; } = null!;

    public string id_producto { get; set; } = null!;

    public string no_producto { get; set; } = null!;

    public string descripcion_producto { get; set; } = null!;

    public decimal cantidad_origen { get; set; }

    public decimal cantidad_recibida { get; set; }
}