// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bellon.API.Liquidacion.DataBase.Models;

[Table("TipoContenedores", Schema = "Liquidacion")]
[Index("descripcion", Name = "UQ__TipoCont__298336B6CC446320", IsUnique = true)]
public partial class TipoContenedores
{
    [Key]
    public int id_tipo_contenedor { get; set; }

    [StringLength(100)]
    public string descripcion { get; set; } = null!;

    public bool estado { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fecha_creado { get; set; }

    [StringLength(100)]
    public string creado_por { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime? fecha_modificado { get; set; }

    [StringLength(100)]
    public string? modificado_por { get; set; }

    [InverseProperty("tipo_contenedor")]
    public virtual ICollection<CabeceraTransito> CabeceraTransito { get; set; } = new List<CabeceraTransito>();

    [InverseProperty("tipo_contenedor")]
    public virtual ICollection<HistCabeceraTransitos> HistCabeceraTransitos { get; set; } = new List<HistCabeceraTransitos>();
}